inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
    - 'spec/**/*'
Documentation:
  Enabled: false
AllCops:
  SuggestExtensions: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes 
Bundler/OrderedGems:
  Exclude:
    - Gemfile
Layout/LineLength:
  Max: 120
